name: Publish Theme to cPanel

on:
  push:
    branches:
      - prod

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy Theme via FTP to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SWAPNAGAR_SERVER }}
          username: ${{ secrets.FTP_SWAPNAGAR_USER }}
          password: ${{ secrets.FTP_SWAPNAGAR_PASS }}
          local-dir: wp-content/themes/swapnanagar/ # Local theme folder in your repo
          server-dir: public_html/swapnanagar-theme/wp-content/themes/swapnanagar/ # Exact path to theme on server
